When I install ion-autocomplete with NPM I get the follow error, because npm run the test command after installing:
npm install ion-autocomplete
-
> ion-autocomplete@0.3.0 install /home/everton/programacao/node_modules/ion-autocomplete
> node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

module.js:338
    throw err;
    ^

Error: Cannot find module '/home/everton/programacao/node_modules/ion-autocomplete/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager'